workdir: example/analysis/
data:  ../config/samples.csv

phase : True

genome :
    S2Rplus : ../genome/BDGP6.28.fa.gz

phased_vcf:
    # S2Rplus : ../analysis/phasedVCFs/S2Rplus-phased.vcf

bigWig :
    CP190 : ../genome/CP190-dm6.bw    # GSM762836
    Beaf-32 : ../genome/Beaf32-dm6.bw # GSM762845
    CTCF : ../genome/CTCF-dm6.bw      # GSM1535983
bed :
    Genes : ../genome/BDGP6.28.99.genes.bed
plot_coordinates: ../config/plot_coordinates.bed

protocol:
    regions: ../config/regions.bed
    re1 : DpnII
    re1_seq : '^GATC'
    re2:
    re2_seq:
    arima: False

cutadapt:
    forwardAdapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
    reverseAdapter: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
    overlap: 6
    errorRate: 0.1
    minimumLength: 20
    qualityCutoff: 20
    GCcontent: 43

hicup:
    shortest: 150
    longest: 850
    nofill: False

colourmap : 'Purples'

HiCcompare:
    fdr: 0.1
    logFC: 0
    multi: True

compareMatrices:
    vMin: -1.96
    vMax: 1.96
    size: 3


createValidBam: False
binsize : [1000, 3000]
multiQCconfig : ../config/multiqc_config.yaml
fastq_screen :
