__default__:
  account: "free"
  partition: "batch"
  ntasks: 1
  cpus-per-task: 16
  job-name: "{rule}-%j"
  mail-type: "ALL"
  mail-user: "sr467@bath.ac.uk"
  output: "slurm-%j-%x.out"
  error: "slurm-%j-%x.err"
  account : "free"
  partition : "batch"
  time : 60

HiCcompare:
  time : 180

whatshap:
  time : 360

haplotag:
  time : 360

hicupTruncate:
  time : 60

cutadapt:
  time : 120

hicupMap:
  time : 360

hicupFilter:
  time : 240

hicupDeduplicate:
  time : 180

detectLoops:
  time : 120

baseRecalibrator:
  time : 360

applyBQSR:
  time : 360

haplotypeCaller:
  time : 360

variantRecalibratorSNPs:
  time : 360

variantRecalibratorINDELS:
  time : 360

bowtie2Build:
  time : 120

deduplicate:
  time : 360

buildBaseMatrix:
  time : 120
  partition : "batch-128gb"

HiCRep:
  time : 360

run_hapcompass:
  partition : "batch-128gb"
  time : 360

SNPsplit:
  time : 360

hifive:
  time : 360
