
workdir: /home/u/sr467/scratch/projects/HiC-new-pipeline
threads : 16
data:
    samples: /home/u/sr467/scratch/projects/HiC-new-pipeline/config/cluster-samples.csv
    phased_vcf: /home/u/sr467/scratch/projects/HiC-new-pipeline/config/cluster-phased-vcfs.csv
genome :
    table : /home/u/sr467/scratch/projects/HiC-new-pipeline/config/genomes.csv
    genes : /home/u/sr467/scratch/projects/genomes/GRCh38/annotation/gencode.v33.annotation.bed
    ctcf : [/home/u/sr467/scratch/projects/genomes/GRCh38/annotation/wgEncodeUwTfbsMcf7CtcfStdRawRep1_grch38.bw.bw,
            /home/u/sr467/scratch/projects/genomes/GRCh38/annotation/wgEncodeUwTfbsMcf7CtcfStdRawRep2_grch38.bw.bw]
    ctcf_orient : [/home/u/sr467/scratch/projects/genomes/GRCh38/annotation/MCF-7_CTCF-merged.bed]
protocol:
    regions: /home/u/sr467/scratch/projects/HiC-new-pipeline/config/regions-all.bed
    re1 : Mbo1
    re1_seq : '^GATC'
    re2:
    re2_seq:
    arima:
hicup:
    shortest:
    longest:
    nofill: False
HiCcompare:
    fdr: 0.01
    logFC: 0
fastq_screen : /home/u/sr467/scratch/projects/HiC-new-pipeline/config/fastq_screen.config
#binsize : [1000, 3000, 10000]
binsize : [5000, 10000, 50000]
known_sites: ['/home/u/sr467/scratch/projects/genomes/hg38/dbsnp_146.hg38.vcf.gz',
              '/home/u/sr467/scratch/projects/genomes/hg38/1000G_phase1.snps.high_confidence.hg38.vcf.gz',
              '/home/u/sr467/scratch/projects/genomes/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz']
tmpdir: /home/u/sr467/scratch/tmp
