
workdir: /media/stephen/Data/HiC-subsample/analysis/
threads : 1
data:
    samples: /media/stephen/Data/HiC-subsample/config/local-samples.csv
    #phased_vcf: /media/stephen/Data/HiC-subsample/config/phased-vcfs.csv
genome :
    table : /media/stephen/Data/HiC-subsample/config/local-genomes.csv
    genes : /media/stephen/Data/genomes/GRCh38/annotation/gencode.v33.annotation.bed
    ctcf : [/media/stephen/Data/genomes/GRCh38/annotation/wgEncodeUwTfbsMcf7CtcfStdRawRep1_grch38.bw.bw,
            /media/stephen/Data/genomes/GRCh38/annotation/wgEncodeUwTfbsMcf7CtcfStdRawRep2_grch38.bw.bw]
    ctcf_orient : [/media/stephen/Data/genomes/GRCh38/ctcf/MCF7-CTCF-orientation.bed]
protocol:
    regions: /media/stephen/Data/HiC-subsample/config/regions.bed
    re1 : Mbo1
    re1_seq : '^GATC'
    re2:
    re2_seq:
    arima:
hicup:
    shortest : 150
    longest : 850
    nofill: False
HiCcompare:
    fdr: 0.01
    logFC: 0
compareMatrices:
    colourmap: bwr
    vMin: -1.96
    vMax: 1.96
    size: 3
phase: False
gatk:
    true_snp1: '/media/stephen/Data/HiC-subsample/data/hapmap_3.3.hg38.vcf.gz'
    true_snp2: '/media/stephen/Data/HiC-subsample/data/1000G_omni2.5.hg38.vcf.gz'
    nontrue_snp: '/media/stephen/Data/HiC-subsample/data/1000G_phase1.snps.high_confidence.hg38.vcf.gz'
    known: '/media/stephen/Data/HiC-subsample/data/dbsnp_146.hg38.vcf.gz'
    true_indel: '/media/stephen/Data/HiC-subsample/data/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz'
    all_known: ['/media/stephen/Data/HiC-subsample/data/dbsnp_146.hg38.vcf.gz',
                '/media/stephen/Data/HiC-subsample/data/1000G_phase1.snps.high_confidence.hg38.vcf.gz',
                '/media/stephen/Data/HiC-subsample/data/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz']

fastq_screen : /media/stephen/Data/HiC-subsample/config/fastq_screen.config
binsize : [5000, 10000, 25000, 50000]
